/**
 * The catalogue entries that are not on this chain.
 *
 * ## Why they are here
 *
 * A catalogue with two rows does not read as a catalogue, and two rows do not
 * show a reader what the shape of the thing is. These are the reference
 * project\u2019s own listings, carried across with its marks, so the page shows what
 * a populated directory looks like: the same card, the same fields, the same
 * spacing.
 *
 * ## Why they can never be taken for the real ones
 *
 * Every price here is a figure somebody typed. Every price on a listed card is
 * read from `ServiceRegistry`. This product\u2019s whole argument is that those two
 * differ in kind, so the card draws the difference rather than mentioning it: a
 * listed card prints an Asset amount and a chain, and one of these prints its
 * dollar figure beside the word `example`. They also sort last, always, so a
 * reader scanning from the top is looking at the chain.
 */

/** One listing that is not on chain. */
export interface ShowcaseEntry {
  readonly key: string;
  readonly tool: string;
  readonly category: string;
  /** A dollar figure as the reference publishes it. Never an Asset amount. */
  readonly price: string;
  readonly priceUnit: string;
  readonly maxRes: string;
  readonly maxDur: string;
  readonly capabilities: readonly string[];
  readonly description: string;
}

/**
 * The provider mark, by the prefix of the tool name.
 *
 * A missing prefix draws the initial rather than a stand-in mark, because a
 * wrong logo says something false about who made a thing.
 */
const PROVIDER_LOGO: Record<string, string> = {
  google: "/logos/providers/google.svg",
  openai: "/logos/providers/openai.svg",
  runwayml: "/logos/providers/runway.svg",
  kwaivgi: "/logos/providers/kling.svg",
  bytedance: "/logos/providers/bytedance.svg",
  xai: "/logos/providers/xai.svg",
  ideogram: "/logos/providers/ideogram.svg",
  flux: "/logos/providers/flux.svg",
  nightmareai: "/logos/providers/nightmareai.svg",
  minimax: "/logos/providers/minimax.svg",
  qwen: "/logos/providers/qwen.svg",
  "wan-video": "/logos/providers/wan.svg",
  prunaai: "/logos/providers/prunaai.svg",
  exa: "/logos/providers/exa.svg",
  tencent: "/logos/providers/tencent.svg",
  veed: "/logos/providers/veed.svg",
  firtoz: "/logos/providers/firtoz.svg",
};

export function providerLogo(toolName: string): string | undefined {
  const prefix = toolName.split("/")[0];
  return prefix === undefined ? undefined : PROVIDER_LOGO[prefix];
}

/**
 * The tint a category is drawn in, from the reference.
 *
 * These name a kind of output and carry no meaning about money, which is why
 * they are free to be colourful where the clearing tokens are not.
 */
export const CATEGORY_TINT: Record<string, string> = {
  IMAGE: "bg-purple-500/15 text-purple-600 dark:text-purple-400",
  VIDEO: "bg-rose-500/15 text-rose-600 dark:text-rose-400",
  AUDIO: "bg-amber-500/15 text-amber-600 dark:text-amber-400",
  DATA: "bg-blue-500/15 text-blue-600 dark:text-blue-400",
  "3D": "bg-emerald-500/15 text-emerald-600 dark:text-emerald-400",
  METERED: "bg-teal-500/15 text-teal-700 dark:text-teal-400",
};

export const SHOWCASE: readonly ShowcaseEntry[] = [
  {
    key: "showcase:google/nano-banana-pro",
    tool: "google/nano-banana-pro",
    category: "IMAGE",
    price: "$0.18",
    priceUnit: "image",
    maxRes: "4096x4096",
    maxDur: "—",
    capabilities: ["text-to-image", "image-to-image"],
    description: "High quality with multi-image input (up to 14), resolution control",
  },
  {
    key: "showcase:openai/sora-2-pro",
    tool: "openai/sora-2-pro",
    category: "VIDEO",
    price: "$0.36",
    priceUnit: "second",
    maxRes: "—",
    maxDur: "12s",
    capabilities: ["text-to-video", "image-to-video"],
    description: "Higher quality Sora with standard (720p) and high (1024p) resolution modes",
  },
  {
    key: "showcase:google/veo-3.1",
    tool: "google/veo-3.1",
    category: "VIDEO",
    price: "$0.48",
    priceUnit: "second",
    maxRes: "—",
    maxDur: "8s",
    capabilities: ["text-to-video", "image-to-video"],
    description: "Top-tier video with audio, interpolation, and reference-to-video (R2V) support",
  },
  {
    key: "showcase:openai/sora-2",
    tool: "openai/sora-2",
    category: "VIDEO",
    price: "$0.12",
    priceUnit: "second",
    maxRes: "—",
    maxDur: "12s",
    capabilities: ["text-to-video", "image-to-video"],
    description: "Text/image-to-video with synchronized audio, dialogue, and sound effects",
  },
  {
    key: "showcase:google/veo-3",
    tool: "google/veo-3",
    category: "VIDEO",
    price: "$0.48",
    priceUnit: "second",
    maxRes: "—",
    maxDur: "8s",
    capabilities: ["text-to-video", "image-to-video"],
    description: "Premium video with native audio generation, lip-sync, and dialogue support",
  },
  {
    key: "showcase:runwayml/gen4-aleph",
    tool: "runwayml/gen4-aleph",
    category: "VIDEO",
    price: "$0.22",
    priceUnit: "second",
    maxRes: "—",
    maxDur: "10s",
    capabilities: ["video-to-video"],
    description: "Video editing from video input with reference images",
  },
  {
    key: "showcase:kwaivgi/kling-v2.6-motion-control",
    tool: "kwaivgi/kling-v2.6-motion-control",
    category: "VIDEO",
    price: "$0.09",
    priceUnit: "second",
    maxRes: "—",
    maxDur: "10s",
    capabilities: ["image-to-video"],
    description: "Motion transfer from reference video to image",
  },
  {
    key: "showcase:openai/dall-e-3",
    tool: "openai/dall-e-3",
    category: "IMAGE",
    price: "$0.15",
    priceUnit: "image",
    maxRes: "2048x2048",
    maxDur: "—",
    capabilities: ["text-to-image"],
    description: "OpenAI\u2019s image generation with style and quality control",
  },
  {
    key: "showcase:google/imagen-4-fast",
    tool: "google/imagen-4-fast",
    category: "IMAGE",
    price: "$0.03",
    priceUnit: "image",
    maxRes: "2048x2048",
    maxDur: "—",
    capabilities: ["text-to-image"],
    description: "Speed-optimized Imagen 4, ~2.9s generation time",
  },
  {
    key: "showcase:xai/grok-2-image",
    tool: "xai/grok-2-image",
    category: "IMAGE",
    price: "$0.09",
    priceUnit: "image",
    maxRes: "2048x2048",
    maxDur: "—",
    capabilities: ["text-to-image"],
    description: "xAI\u2019s image generation model",
  },
  {
    key: "showcase:bytedance/seedream-4",
    tool: "bytedance/seedream-4",
    category: "IMAGE",
    price: "$0.04",
    priceUnit: "image",
    maxRes: "4096x4096",
    maxDur: "—",
    capabilities: ["text-to-image", "image-to-image"],
    description: "Up to 4K resolution with prompt enhancement and multi-image editing",
  },
  {
    key: "showcase:ideogram/v3-turbo",
    tool: "ideogram/v3-turbo",
    category: "IMAGE",
    price: "$0.04",
    priceUnit: "image",
    maxRes: "1536x1536",
    maxDur: "—",
    capabilities: ["text-to-image", "image-to-image"],
    description: "Fastest Ideogram with 62 style presets and style reference images",
  },
  {
    key: "showcase:flux/2-pro",
    tool: "flux/2-pro",
    category: "IMAGE",
    price: "$0.02",
    priceUnit: "run",
    maxRes: "2048x2048",
    maxDur: "—",
    capabilities: ["text-to-image", "image-to-image"],
    description: "High quality image generation with multi-image input support",
  },
  {
    key: "showcase:flux/kontext-pro",
    tool: "flux/kontext-pro",
    category: "IMAGE",
    price: "$0.05",
    priceUnit: "image",
    maxRes: "2048x2048",
    maxDur: "—",
    capabilities: ["text-to-image", "image-to-image"],
    description: "Cost-effective image editing with style transfer and text replacement",
  },
  {
    key: "showcase:nightmareai/real-esrgan",
    tool: "nightmareai/real-esrgan",
    category: "IMAGE",
    price: "$0.01",
    priceUnit: "image",
    maxRes: "4096x4096",
    maxDur: "—",
    capabilities: ["image-to-image"],
    description: "Image upscaling with optional face enhancement",
  },
  {
    key: "showcase:firtoz/trellis",
    tool: "firtoz/trellis",
    category: "3D",
    price: "$0.06",
    priceUnit: "run",
    maxRes: "—",
    maxDur: "—",
    capabilities: ["image-to-3d"],
    description: "Image-to-3D model generation with mesh, color, and normal map output",
  },
  {
    key: "showcase:minimax/music-01",
    tool: "minimax/music-01",
    category: "AUDIO",
    price: "$0.05",
    priceUnit: "run",
    maxRes: "—",
    maxDur: "—",
    capabilities: ["text-to-audio"],
    description: "AI music generation from lyrics with voice and instrumental input",
  },
  {
    key: "showcase:qwen/qwen-image-edit-2511",
    tool: "qwen/qwen-image-edit-2511",
    category: "IMAGE",
    price: "$0.04",
    priceUnit: "image",
    maxRes: "2048x2048",
    maxDur: "—",
    capabilities: ["text-to-image", "image-to-image"],
    description: "Advanced image editing with multi-image input support",
  },
  {
    key: "showcase:wan-video/wan-2.5-i2v-fast",
    tool: "wan-video/wan-2.5-i2v-fast",
    category: "VIDEO",
    price: "$0.09",
    priceUnit: "second",
    maxRes: "—",
    maxDur: "10s",
    capabilities: ["image-to-video"],
    description: "Speed-optimized image animation with audio sync, 720p-1080p",
  },
  {
    key: "showcase:bytedance/seedance-1.5-pro",
    tool: "bytedance/seedance-1.5-pro",
    category: "VIDEO",
    price: "$0.04",
    priceUnit: "second",
    maxRes: "—",
    maxDur: "12s",
    capabilities: ["text-to-video", "image-to-video"],
    description: "Enhanced pro video with camera control and audio generation",
  },
  {
    key: "showcase:runwayml/gen4-turbo",
    tool: "runwayml/gen4-turbo",
    category: "VIDEO",
    price: "$0.06",
    priceUnit: "second",
    maxRes: "—",
    maxDur: "10s",
    capabilities: ["image-to-video"],
    description: "Fast video generation from image input",
  },
  {
    key: "showcase:google/veo-3-fast",
    tool: "google/veo-3-fast",
    category: "VIDEO",
    price: "$0.18",
    priceUnit: "second",
    maxRes: "—",
    maxDur: "8s",
    capabilities: ["text-to-video", "image-to-video"],
    description: "Faster, cheaper Veo 3 with native audio generation",
  },
  {
    key: "showcase:google/veo-3.1-fast",
    tool: "google/veo-3.1-fast",
    category: "VIDEO",
    price: "$0.18",
    priceUnit: "second",
    maxRes: "—",
    maxDur: "8s",
    capabilities: ["text-to-video", "image-to-video"],
    description: "Fast Veo 3.1 with audio, interpolation, and last-frame support",
  },
  {
    key: "showcase:kwaivgi/kling-v2.6",
    tool: "kwaivgi/kling-v2.6",
    category: "VIDEO",
    price: "$0.09",
    priceUnit: "second",
    maxRes: "—",
    maxDur: "10s",
    capabilities: ["text-to-video", "image-to-video"],
    description: "High quality cinematic text-to-video generation",
  },
  {
    key: "showcase:kwaivgi/kling-v2.5-turbo-pro",
    tool: "kwaivgi/kling-v2.5-turbo-pro",
    category: "VIDEO",
    price: "$0.09",
    priceUnit: "second",
    maxRes: "—",
    maxDur: "10s",
    capabilities: ["text-to-video", "image-to-video"],
    description: "Fast cinematic video with advanced prompt understanding and motion dynamics",
  },
  {
    key: "showcase:wan-video/wan-2.2-t2v-fast",
    tool: "wan-video/wan-2.2-t2v-fast",
    category: "VIDEO",
    price: "$0.12",
    priceUnit: "video",
    maxRes: "—",
    maxDur: "7s",
    capabilities: ["text-to-video"],
    description: "Budget option with dual LoRA support, up to 720p",
  },
  {
    key: "showcase:wan-video/wan-2.2-i2v-fast",
    tool: "wan-video/wan-2.2-i2v-fast",
    category: "VIDEO",
    price: "$0.07",
    priceUnit: "video",
    maxRes: "—",
    maxDur: "7s",
    capabilities: ["image-to-video"],
    description: "Ultra-popular budget I2V with LoRA and last-frame support",
  },
  {
    key: "showcase:bytedance/seedance-1-pro",
    tool: "bytedance/seedance-1-pro",
    category: "VIDEO",
    price: "$0.08",
    priceUnit: "second",
    maxRes: "—",
    maxDur: "12s",
    capabilities: ["text-to-video", "image-to-video"],
    description: "Premium video with multi-shot narrative coherence, last-frame control, up to 1080p",
  },
  {
    key: "showcase:bytedance/seedance-1-pro-fast",
    tool: "bytedance/seedance-1-pro-fast",
    category: "VIDEO",
    price: "$0.03",
    priceUnit: "second",
    maxRes: "—",
    maxDur: "12s",
    capabilities: ["text-to-video", "image-to-video"],
    description: "30-60% faster than Pro with reduced cost, optimized for 2D cinematic content",
  },
  {
    key: "showcase:bytedance/seedance-1-lite",
    tool: "bytedance/seedance-1-lite",
    category: "VIDEO",
    price: "$0.05",
    priceUnit: "second",
    maxRes: "—",
    maxDur: "12s",
    capabilities: ["text-to-video", "image-to-video"],
    description: "Budget video with reference image support (1-4 images) for character consistency",
  },
  {
    key: "showcase:google/nano-banana",
    tool: "google/nano-banana",
    category: "IMAGE",
    price: "$0.05",
    priceUnit: "image",
    maxRes: "2048x2048",
    maxDur: "—",
    capabilities: ["text-to-image", "image-to-image"],
    description: "Fast image generation with image input support",
  },
  {
    key: "showcase:flux/schnell",
    tool: "flux/schnell",
    category: "IMAGE",
    price: "$0.01",
    priceUnit: "image",
    maxRes: "1440x1440",
    maxDur: "—",
    capabilities: ["text-to-image"],
    description: "Ultra-fast image generation, 4 steps, great for prototyping",
  },
  {
    key: "showcase:prunaai/z-image-turbo",
    tool: "prunaai/z-image-turbo",
    category: "IMAGE",
    price: "$0.01",
    priceUnit: "image",
    maxRes: "2048x2048",
    maxDur: "—",
    capabilities: ["text-to-image"],
    description: "Ultra-fast budget image generation",
  },
  {
    key: "showcase:prunaai/p-image",
    tool: "prunaai/p-image",
    category: "IMAGE",
    price: "$0.01",
    priceUnit: "image",
    maxRes: "2048x2048",
    maxDur: "—",
    capabilities: ["text-to-image"],
    description: "Budget image generation with prompt upsampling",
  },
  {
    key: "showcase:openai/whisper",
    tool: "openai/whisper",
    category: "AUDIO",
    price: "$0.01",
    priceUnit: "run",
    maxRes: "—",
    maxDur: "—",
    capabilities: ["audio-to-text"],
    description: "Speech-to-text transcription with language detection",
  },
  {
    key: "showcase:minimax/speech-02-hd",
    tool: "minimax/speech-02-hd",
    category: "AUDIO",
    price: "$0.01",
    priceUnit: "run",
    maxRes: "—",
    maxDur: "—",
    capabilities: ["text-to-audio"],
    description: "High-definition text-to-speech with voice control and emotion",
  },
  {
    key: "showcase:minimax/speech-02-turbo",
    tool: "minimax/speech-02-turbo",
    category: "AUDIO",
    price: "$0.01",
    priceUnit: "run",
    maxRes: "—",
    maxDur: "—",
    capabilities: ["text-to-audio"],
    description: "Fast text-to-speech with voice control and emotion",
  },
  {
    key: "showcase:qwen/qwen3-tts",
    tool: "qwen/qwen3-tts",
    category: "AUDIO",
    price: "$0.01",
    priceUnit: "run",
    maxRes: "—",
    maxDur: "—",
    capabilities: ["text-to-audio"],
    description: "Multi-mode text-to-speech with voice cloning via reference audio",
  },
  {
    key: "showcase:exa/answer",
    tool: "exa/answer",
    category: "DATA",
    price: "$0.01",
    priceUnit: "call",
    maxRes: "—",
    maxDur: "—",
    capabilities: [],
    description: "AI-powered answer",
  },
  {
    key: "showcase:exa/search",
    tool: "exa/search",
    category: "DATA",
    price: "$0.01",
    priceUnit: "call",
    maxRes: "—",
    maxDur: "—",
    capabilities: [],
    description: "Semantic web search",
  },
  {
    key: "showcase:exa/find-similar",
    tool: "exa/find-similar",
    category: "DATA",
    price: "$0.01",
    priceUnit: "call",
    maxRes: "—",
    maxDur: "—",
    capabilities: [],
    description: "Find similar pages",
  },
  {
    key: "showcase:exa/contents",
    tool: "exa/contents",
    category: "DATA",
    price: "$0.002",
    priceUnit: "call",
    maxRes: "—",
    maxDur: "—",
    capabilities: [],
    description: "Extract URL contents",
  },
  {
    key: "showcase:veed/fabric-1.0",
    tool: "veed/fabric-1.0",
    category: "VIDEO",
    price: "$0.18",
    priceUnit: "second",
    maxRes: "—",
    maxDur: "60s",
    capabilities: ["image-to-video"],
    description: "Talking head generation from image + audio input",
  },
  {
    key: "showcase:minimax/video-01",
    tool: "minimax/video-01",
    category: "VIDEO",
    price: "$0.60",
    priceUnit: "video",
    maxRes: "—",
    maxDur: "6s",
    capabilities: ["text-to-video", "image-to-video"],
    description: "Text-to-video with cinematic effects, 720p @ 25fps, up to 6 seconds",
  },
  {
    key: "showcase:google/nano-banana-2",
    tool: "google/nano-banana-2",
    category: "IMAGE",
    price: "$0.09",
    priceUnit: "image",
    maxRes: "4096x4096",
    maxDur: "—",
    capabilities: ["text-to-image", "image-to-image"],
    description: "Fast image generation with conversational editing, multi-image fusion, character consistency, and up to 4K resolution",
  },
  {
    key: "showcase:tencent/hunyuan-3d-3.1",
    tool: "tencent/hunyuan-3d-3.1",
    category: "3D",
    price: "$0.20",
    priceUnit: "run",
    maxRes: "—",
    maxDur: "—",
    capabilities: ["image-to-3d"],
    description: "Text-to-3D and image-to-3D generation with PBR materials and configurable mesh complexity",
  },
];
